-- =====================================================================
-- 잇다(Itda) — 권승훈 파트 스키마 (No.25~32: 장소 / 일정·플래너)
--   * 재기동마다 깨끗하게 다시 만들기 위해 DROP 후 CREATE.
--   * content / bookmark 는 박세현 소유. 여기선 조인/조회용 최소 placeholder.
--     (실제 DDL 확정되면 삭제하고 그쪽 것으로 대체)
--   * fee(입장료) 컬럼 없음 — v2 제거 확정.
--   * bookmark 는 v3부터 '장소 전용'(v4 기준) → 내 No.25 is_bookmarked 계산이 의존.
-- =====================================================================

DROP TABLE IF EXISTS itinerary_place CASCADE;
DROP TABLE IF EXISTS itinerary CASCADE;
DROP TABLE IF EXISTS content_place CASCADE;
DROP TABLE IF EXISTS place_image CASCADE;
DROP TABLE IF EXISTS bookmark CASCADE;
DROP TABLE IF EXISTS content CASCADE;
DROP TABLE IF EXISTS place CASCADE;

-- ---------------------------------------------------------------------
-- place (내 소유 · 팀 공유 DDL)
--   박세현/김다연도 이 테이블을 조회하므로 이 정의를 받아쓴다.
-- ---------------------------------------------------------------------
CREATE TABLE place (
    place_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200)     NOT NULL,
    category        VARCHAR(50),
    description     TEXT,
    latitude        DOUBLE PRECISION NOT NULL,
    longitude       DOUBLE PRECISION NOT NULL,
    address         VARCHAR(300),
    region          VARCHAR(50),
    opening_hours   VARCHAR(200),
    kakao_place_id  VARCHAR(50),
    created_at      TIMESTAMP        NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP        NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- place_image (내 소유)
-- ---------------------------------------------------------------------
CREATE TABLE place_image (
    place_image_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id        BIGINT       NOT NULL REFERENCES place(place_id) ON DELETE CASCADE,
    image_url       VARCHAR(500) NOT NULL,
    is_primary      BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order      INT          NOT NULL DEFAULT 0
);
CREATE INDEX idx_place_image_place ON place_image(place_id);

-- ---------------------------------------------------------------------
-- content (박세현 소유 · placeholder)
--   내 API 는 thumbnail_url, title 만 조인해서 씀.
-- ---------------------------------------------------------------------
CREATE TABLE content (
    content_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(200),
    thumbnail_url  VARCHAR(500),
    created_at     TIMESTAMP NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- content_place (콘텐츠 ↔ 장소 매핑, recommend_order)
-- ---------------------------------------------------------------------
CREATE TABLE content_place (
    content_place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id       BIGINT NOT NULL REFERENCES content(content_id) ON DELETE CASCADE,
    place_id         BIGINT NOT NULL REFERENCES place(place_id)     ON DELETE CASCADE,
    recommend_order  INT    NOT NULL
);
CREATE INDEX idx_content_place_content ON content_place(content_id, recommend_order);

-- ---------------------------------------------------------------------
-- bookmark (박세현 소유 · placeholder) — v3부터 장소 전용
-- ---------------------------------------------------------------------
CREATE TABLE bookmark (
    bookmark_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    place_id     BIGINT NOT NULL REFERENCES place(place_id) ON DELETE CASCADE,
    created_at   TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_bookmark_user_place UNIQUE (user_id, place_id)
);

-- ---------------------------------------------------------------------
-- itinerary (내 소유)
--   user_id 는 FK 엔티티 대신 Long 값 보관 (안시현 User 와 나중에 합칠 때 충돌 방지)
--   deleted_at: soft delete (커뮤니티 공유/리뷰 FK 무결성)
-- ---------------------------------------------------------------------
CREATE TABLE itinerary (
    itinerary_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT       NOT NULL,
    content_id           BIGINT       REFERENCES content(content_id),
    title                VARCHAR(200) NOT NULL,
    travel_date          DATE,
    region               VARCHAR(50),
    duration_label       VARCHAR(50),
    is_shared            BOOLEAN      NOT NULL DEFAULT FALSE,
    source_itinerary_id  BIGINT,
    deleted_at           TIMESTAMP,
    created_at           TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP    NOT NULL DEFAULT now()
);
-- (partial index 는 H2 미지원 → 단일 schema.sql 로 PG/H2 모두 쓰기 위해 일반 인덱스)
CREATE INDEX idx_itinerary_user ON itinerary(user_id);

-- ---------------------------------------------------------------------
-- itinerary_place (내 소유)
--   status: PENDING | CONFIRMED | CHANGED
-- ---------------------------------------------------------------------
CREATE TABLE itinerary_place (
    itinerary_place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itinerary_id       BIGINT      NOT NULL REFERENCES itinerary(itinerary_id) ON DELETE CASCADE,
    place_id           BIGINT      NOT NULL REFERENCES place(place_id),
    day_number         INT         NOT NULL DEFAULT 1,
    visit_order        INT         NOT NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    memo               VARCHAR(500)
);
CREATE INDEX idx_itinerary_place_itinerary ON itinerary_place(itinerary_id, day_number, visit_order);
